"""
Marimo integration template - bootstraps ``src`` on ``sys.path`` and wires up the repo's Envs/Logger/
ApplicationConfig singletons, then demonstrates marimo's reactive execution model with a UI slider.

This notebook is the copy source for ``marimo/raw/playground_marimo.py`` (created by ``make create-venv``) and
is meant to be a sensible, generic starting point: keep it runnable standalone, from ``make marimo``, or opened
directly through the marimo UI, regardless of the process current working directory.
"""

import marimo

__generated_with = "0.23.14"
app = marimo.App()


@app.cell
def _():
    """
    Imports marimo's UI/markdown namespace under its conventional alias.

    :return: tuple. Single-element tuple exposing ``mo`` to later cells.
    """
    import marimo as mo

    return (mo,)


@app.cell
def _(mo):
    """
    Renders the notebook title and a short orientation blurb.

    :param mo: module. marimo's public namespace.
    """
    mo.md(
        """
        # Marimo Template Notebook

        Integration reference for wiring this repository's `src` package into a marimo notebook. See
        `marimo/documentation/documentation_notebook.py` for a fuller explanation of marimo's reactive
        execution model and how this workflow differs from the jupytext-paired Jupyter notebooks under
        `notebooks/`.
        """
    )
    return


@app.cell
def _():
    """
    Walks up from this file's own location to the repository root and inserts it onto ``sys.path``.

    Unlike the Jupyter templates (``notebooks/template/*.py``), which append ``os.getcwd()``-relative
    ``".."``/``"../.."`` entries - a hack that only works if the notebook happens to be launched from a
    predictable current working directory - this walk is anchored to ``__file__``. It is therefore identical
    whether the notebook is launched via ``make marimo`` (which ``cd``s into ``marimo/`` first), the marimo UI
    directly, or ``uv run marimo edit marimo/template/template_notebook.py`` from the repo root: the marker
    search finds the same repository root regardless of the process current working directory. Mirrors the
    marker-file logic in ``src/utils/project_paths.py``, hand-rolled here since ``src`` is not importable yet.
    :return: tuple. Single-element tuple exposing the resolved repository root ``Path``.
    """
    import sys
    from pathlib import Path

    _marker_file_names = ("pyproject.toml", ".git")

    def _find_repo_root(start: Path) -> Path:
        """
        Returns the first parent of start (including start itself) containing a marker file.

        :param start: Path. Directory to begin the upward search from.
        :return: Path. Resolved absolute path of the marker directory.
        """
        for candidate in (start, *start.parents):
            if any((candidate / marker).exists() for marker in _marker_file_names):
                return candidate
        error_msg = f"Could not locate project root: none of {_marker_file_names} found in any parent of {start}."
        raise FileNotFoundError(error_msg)

    project_root = _find_repo_root(Path(__file__).resolve().parent)
    if str(project_root) not in sys.path:
        sys.path.insert(0, str(project_root))
    return (project_root,)


@app.cell
def _(project_root):
    """
    Instantiates the repo's Envs/Logger/ApplicationConfig singletons now that ``src`` is importable.

    Uses the tracked "python_repo"/"logger_file_limit_console" profiles (rather than the git-ignored
    "python_personal" one generated by ``make create-venv``) so this notebook loads correctly the first time it
    is opened, before any personal setup has run.
    :param project_root: Path. Repository root discovered by the bootstrap cell, used only to confirm the
        bootstrap ran before importing from ``src``.
    :return: tuple. The singleton instances and loaded config data, exposed to later cells.
    """
    from src.utils.application_config import ApplicationConfig
    from src.utils.envs import Envs
    from src.utils.logger import Logger

    logger_config_name = "logger_file_limit_console"
    python_config_name = "python_repo"

    envs = Envs()
    envs.set_logger(logger_config_name)
    envs.set_config(python_config_name)

    logger = Logger()
    logger.start_timer(f"MARIMO NOTEBOOK; repository root: {project_root}")

    config = ApplicationConfig()
    config_data = config.get_data()
    return config_data, logger


@app.cell
def _(config_data, mo):
    """
    Displays the active configuration profile name loaded through ``ApplicationConfig``.

    :param config_data: ApplicationConfigData. Loaded configuration data.
    :param mo: module. marimo's public namespace.
    """
    mo.md(f"Loaded configuration profile: **`{config_data.name}`**")
    return


@app.cell
def _(mo):
    """
    Creates a slider UI element to drive the reactive example below.

    :param mo: module. marimo's public namespace.
    :return: tuple. Single-element tuple exposing the slider so its value can be read reactively.
    """
    amplitude_slider = mo.ui.slider(start=1, stop=10, value=3, label="Amplitude")
    amplitude_slider
    return (amplitude_slider,)


@app.cell
def _(amplitude_slider, mo):
    """
    Reruns automatically whenever ``amplitude_slider`` changes, demonstrating marimo's reactive execution.

    This cell references ``amplitude_slider.value`` as a free variable, so marimo's dataflow graph reruns it
    every time the slider moves - no manual "run all cells" required, unlike a Jupyter notebook.
    :param amplitude_slider: mo.ui.slider. The slider created in the previous cell.
    :param mo: module. marimo's public namespace.
    """
    mo.md(f"Selected amplitude is **{amplitude_slider.value}**.")
    return


@app.cell
def _(logger):
    """
    Ends the timer started when the Logger singleton was instantiated.

    :param logger: Logger. The Logger singleton instance.
    """
    logger.end_timer()
    return


if __name__ == "__main__":
    app.run()
